pipeline:
  install:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm run lint
  tests:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm run test:ember

when:
  event:
    - pull_request
