matrix:
  scenario:
    - ember-lts-4.12
    - ember-lts-5.8
    - ember-release
    - ember-beta
    - ember-canary
    - embroider-optimized

steps:
  - name: ${scenario}
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm ci
      - npx ember try:one ${scenario}

when:
  event:
    - pull_request

depends_on:
  - test
