matrix:
  scenario:
    - ember-lts-3.24
    - ember-release
    - ember-beta
    - ember-canary
    - ember-classic
    - embroider-safe
    - embroider-optimized

pipeline:
  ${scenario}:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm ci
      - npx ember try:one ${scenario}

when:
  event:
    - pull_request

depends_on:
  - test
