matrix:
  scenario:
    - ember-release
    - ember-beta
    - ember-canary
    - embroider-safe
    - embroider-optimized

pipeline:
  ${scenario}:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm ci
      - npx ember try:one ${scenario}

when:
  event:
    - pull_request

depends_on:
  - test
