matrix:
  scenario:
    - ember-lts-4.12
    - ember-lts-5.8
    - ember-release
    - ember-beta
    - ember-canary
    - embroider-optimized

steps:
  - name: ${scenario}
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm exec ember try:one ${scenario} --skip-cleanup

when:
  event:
    - pull_request

depends_on:
  - test
